name: Feature Request
description: A template for requesting new features, user stories, etc. - as sub-issues of a Bucket
projects: ["nerisaurus/projects/2"]
type: 'Feature'
body:
  - type: markdown
    attributes:
      value: |
        Please provide enough context for PMs and engineers to understand the request.
        Focus on the Problem Statement and Acceptance Criteria; other sections are optional.
        Tip: Keep Acceptance Criteria as short bullet points.
  - type: textarea
    id: problem-statement
    attributes:
      label: '🎯 Problem Statement'
      description: "Format: As a (user) I want (objective) so that (goal). What problem are we solving, for whom, and why does it matter?"
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: '✅ Acceptance Criteria'
      description: "Bullet points listing what is in scope for this story and how we know it’s complete. Prefer concise bullets; Given/When/Then is welcome."
      placeholder: |
        - When X, Y should happen
        - Given A, B ... then C, given D then E...
    validations:
      required: false
  - type: textarea
    id: test-plan
    attributes:
      label: '🧪 Test Plan'
      description: "Optional. Add Given/When/Then scenarios, manual steps, or links to test cases."
    validations:
      required: false
  - type: textarea
    id: out-of-scope
    attributes:
      label: '🚫 Out of Scope'
      description: "Optional. What are we explicitly not doing?"
    validations:
      required: false
  - type: textarea
    id: technical-requirements
    attributes:
      label: '🛠️ Technical Requirements'
      description: "Added by engineering: approach notes, dependencies, risks, and constraints."
    validations:
      required: false