name: Release Candidate Template
description: This creates issues which generate automated Release Candidate PRs.
title: "[ Automated Release Candidate Template ]"
labels:
  - "🔧 Automated Issue (RC)"

body:
  - type: textarea
    id: rc-body
    attributes:
      label: 📒 Notes
      description: Write any additional info or instructions about the Release Candidate here
    validations:
      required: false
