name: Merge Release into Main

on:
  push:
    branches:
      - 'release'

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  main:
    concurrency:
      group: "release to qa backmerge ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
      cancel-in-progress: true
    name: Create PR Release to Main, set to auto-merge if it's viable
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pull-request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --title "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}" --body "Automated Backmerge PR.  This should be enabled to auto-merge if there are no conflicts - if it seems to be lingering, check if manual resolution is needed." --label "🔧 Automated Backmerge"
          TARGET_PR=$(gh pr list --head release --state open --json number -q '.[0].number')
          if [[ -n "$TARGET_PR" ]]; then
            echo "TARGET_PR=$TARGET_PR" >> $GITHUB_ENV
          fi
      - name: enable-auto-merge
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr merge $TARGET_PR --auto --merge
      - name: approve-pr
        uses: actions/github-script@v4
        with:
            github-token: ${{ secrets.GH_PAT }}
            script: |
              const result_approve = await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: process.env.TARGET_PR,
                event: "APPROVE"
              })
              console.log(result_approve.status)
