name: Merge Release into Main

on:
  push:
    branches:
      - 'release'

permissions:
  pull-requests: write

jobs:
  main:
    name: Create PR Release to Main, set to auto-merge if it's viable
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: pull-request
        uses: actions/checkout@v3
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}" --body "Automated Backmerge PR"
          gh pr merge --auto
