name: Merge Release into Main

on:
  push:
    branches:
      - 'release'

permissions:
  pull-requests: write

jobs:
  main:
    name: Create PR Release to Main, set to auto-merge if it's viable
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pull-request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --title "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}" --body "Automated Backmerge PR"
          gh pr merge release --auto --merge
