name: Confirm Safe to Mainline

on:
  push: # for automations getting release --> main
    branches:
      - "release"
  pull_request: # for PRs directly to main
    branches:
      - "main"
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled
      - synchronize

env:
  BRANCH_IS_RELEASE: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/release' ||
    github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'release' }}

jobs:
  Audit-Pull-Request-Mainline:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Release Path
        if: ${{ env.BRANCH_IS_RELEASE == true }}
        run: |
          echo "Release branch is always allowed to merge to main"
          exit 0
      - name: (for bypasses) Checkout Branch
        if: ${{ env.BRANCH_IS_RELEASE != true }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Bypassing Release
        if: ${{ env.BRANCH_IS_RELEASE != true }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          BYPASS_LABEL=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name' | grep '^Can Bypass QA ⚡$' || echo '')
          if [[ -z "$BYPASS_LABEL" ]]; then
            echo "Requires the label 'Can Bypass QA ⚡' to merge directly to main."
            exit 1
          fi
          exit 0
