name: Github PR Audit

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - edited
      - labeled
      - unlabeled

jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = ['Special Label'];
            let labels = context.payload.pull_request.labels;
            const has_bypass_label = labels.filter(l => requiredLabels.includes(l.name)).length === 0;
            const is_release_branch = context.payload.pull_request.head === "release";

            if (!is_release_branch && !has_bypass_label) {
              throw new Error(`Required labels: ${requiredLabels.join(', ')} (or release branch)`);
            }
