name: Confirm Safe to Mainline

on:
  push: # for automations getting release --> main
    branches:
      - "release"
  pull_request: # for PRs directly to main
    branches:
      - "main"
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled
      - synchronize
  pull_request_review: # to update with review status
    types:
      - submitted
      - edited
      - dismissed

env:
  BRANCH_IS_RELEASE: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/release' ||
    github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'release' }}

jobs:
  Audit-Pull-Request-Mainline:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Release Path
        if: ${{ env.BRANCH_IS_RELEASE == true }}
        run: |
          echo "Release branch is always allowed to merge to main"
          exit 0
      - name: (for bypasses) Checkout Branch
        if: ${{ env.BRANCH_IS_RELEASE != true }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Bypassing Release
        if: ${{ env.BRANCH_IS_RELEASE != true }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "it's debug time - started run"
          EVENT_NAME=${{ github.event_name }}
          echo "event name: $EVENT_NAME"
          if [[ "$EVENT_NAME" == "pull_request" ]]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
            echo "PR number: $PR_NUMBER"
          elif [[ "$EVENT_NAME" == "pull_request_review" ]]; then
            PR_NUMBER=${{ github.event.review.pull_request.number }}
          else
            echo "Unsupported event type: $EVENT_NAME"
            exit 1
          fi
          echo "Past PR calculation: PR number: $PR_NUMBER"
          CAN_RUN_GH_PR_AT_ALL=$(gh pr view $PR_NUMBER)
          echo "Can run gh pr view: $CAN_RUN_GH_PR_AT_ALL"
          CAN_RUN_GH_PR_WITH_JSON_ARG=$(gh pr view $PR_NUMBER --json labels)
          echo "Can run gh pr view with json arg: $CAN_RUN_GH_PR_WITH_JSON_ARG"
          CAN_RUN_GH_PR_WITH_Q_ARG=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name')
          echo "Can run gh pr view with q arg: $CAN_RUN_GH_PR_WITH_Q_ARG"
          gh pr view $PR_NUMBER --json labels -q '.labels[].name' | grep -E '^Can Bypass QA ⚡$'
          echo "gh pr view with grep: $?"
          BYPASS_LABEL=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name' | grep -E '^Can Bypass QA ⚡$')
          echo "Bypass label: $BYPASS_LABEL"
          REVIEW_DECISION_JSON=$(gh pr view $PR_NUMBER --json reviewDecision -q '.reviewDecision')
          echo "Review decision JSON: $REVIEW_DECISION_JSON"
          if [[ "$REVIEW_DECISION_JSON" != *"APPROVED"* ]]; then
            echo "PR must have an approved review to merge"
            exit 0 # DEBUG
          fi
          if [[ -z "$BYPASS_LABEL" ]]; then
            echo "Requires the label 'Can Bypass QA ⚡' to merge directly to main.""
            exit 1
          fi
          echo "Bypass label found, proceeding with merge."
          exit 0
