name: Confirm Safe to RC

on:
  push: # for automations getting main --> backmerged into rcs
    branches:
      - "main"
  pull_request: # for PRs of dev branches
    branches-ignore:
      - "main"
      - "release"
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled
      - synchronize
  pull_request_review: # to update with review status
    types:
      - submitted
      - edited
      - dismissed

env:
  BRANCH_IS_MAIN: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' ||
    github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'main' }}

jobs:
  Audit-Pull-Request-Mainline:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Backmerge
        if: ${{ env.BRANCH_IS_MAIN == true }}
        run: |
          echo "main branch doesn't require approvals to backmerge"
          exit 0
      - name: (for non-backmerges) Checkout Branch
        if: ${{ env.BRANCH_IS_MAIN != true }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Non-Backmerges
        if: ${{ env.BRANCH_IS_MAIN != true}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EVENT_NAME=${{ github.event_name }}
          if [[ "$EVENT_NAME" == "pull_request" ]]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
          elif [[ "$EVENT_NAME" == "pull_request_review" ]]; then
            PR_NUMBER=${{ github.event.review.pull_request.number }}
          else
            echo "Unsupported event type: $EVENT_NAME"
            exit 1
          fi
          REVIEW_DECISION_JSON=$(gh pr view $PR_NUMBER --json reviewDecision -q '.reviewDecision')
          if [[ "$REVIEW_DECISION_JSON" != *"APPROVED"* ]]; then
            echo "PR must have an approved review to merge"
            exit 0 # DEBUG
          fi
          exit 0
